site_name: Bio AI Docs

theme:
  name: readthedocs

plugins:
  - search
  - gen-files:
      scripts:
        - docs/scripts/generate_doc_tree.py 
      nav_file: nav.yml
  - mkdocstrings:
      handlers:
        python:
          paths: ["src"]
          options:
            show_source: false
            show_root_heading: true
            separate_signature: true
            docstring_style: google
