from pydantic import BaseModel, Field
from typing import List, Optional
from typing_extensions import Annotated


class QdrantEmbeddingModel(BaseModel):
    """
    Model representing a single vector embedding ready for insertion into Qdrant.
    This is structured to match both Qdrant’s schema expectations and the 
    original block metadata for faceted search or reverse lookup.
    """

    doc_id: Annotated[
        str,
        Field(description="ID of the document this block is part of.")
    ]

    block_id: Annotated[
        str,
        Field(description="Unique identifier for the specific block (e.g., paragraph or sentence).")
    ]

    page: Annotated[
        Optional[int],
        Field(default=None, description="Page number in the source document.")
    ]

    text: Annotated[
        Optional[str],
        Field(default=None, description="Raw block text for reference or debugging.")
    ]

    embedding: Annotated[
        List[float],
        Field(description="Vector representation of the block, generated by BioBERT or equivalent.")
    ]